theme = "PaperMod"
baseURL = 'https://OgalogJP.github.io/'
locale = 'ja-jp'
title = 'Eila Game Lab'

[params]
  env = "production"
  description = "ゲーム制作・Mod制作・技術メモ"
  defaultTheme = "dark"
  showCover = false
  homeInfoMode = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Game Dev"
    url = "/tags/GameDev/"
    weight = 2

  [[menu.main]]
    name = "MOD"
    url = "/tags/MOD/"
    weight = 3

  [[menu.main]]
    name = "Privacy policy"
    url = "/privacy/"
    weight = 4

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5


